[package]
name = "sentinel-test"
version = "0.1.0"
authors = ["Jose Hugo De la cruz Romero <jhugodc@gmail.com>"]
edition = "2018"

[dependencies]
ewasm_api = "0.9"
pwasm-utils = { path = "wasm-utils" }
parity-wasm = "0.31"

[profile.release]
lto = true
